/* tslint:disable */
// generated by typescript-json-validator
import {inspect} from 'util';
import Ajv = require('ajv');
import {RawConfig} from './config';
export const ajv = new Ajv({"allErrors":true,"coerceTypes":false,"format":"fast","nullable":true,"unicode":true,"uniqueItems":true,"useDefaults":true});

ajv.addMetaSchema(require('ajv/lib/refs/json-schema-draft-06.json'));

export {RawConfig};
export const RawConfigSchema = {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "defaultProperties": [
  ],
  "definitions": {
    "TriggerType": {
      "enum": [
        "BRIGHTNESS",
        "STATUS"
      ],
      "type": "string"
    }
  },
  "properties": {
    "box": {
      "defaultProperties": [
      ],
      "properties": {
        "defaultBrightness": {
          "type": "number"
        },
        "inputDebounceDelay": {
          "type": "number"
        },
        "inputsByName": {
          "additionalProperties": {
            "anyOf": [
              {
                "defaultProperties": [
                ],
                "properties": {
                  "mode": {
                    "enum": [
                      "ON_OFF",
                      "TRIGGER"
                    ],
                    "type": "string"
                  },
                  "onStatus": {
                    "type": "string"
                  },
                  "pin": {
                    "type": "number"
                  },
                  "pull": {
                    "enum": [
                      "DOWN",
                      "UP"
                    ],
                    "type": "string"
                  },
                  "trigger": {
                    "defaultProperties": [
                    ],
                    "properties": {
                      "type": {
                        "$ref": "#/definitions/TriggerType"
                      },
                      "value": {
                      }
                    },
                    "required": [
                      "type",
                      "value"
                    ],
                    "type": "object"
                  }
                },
                "required": [
                  "pin"
                ],
                "type": "object"
              },
              {
                "type": "number"
              }
            ]
          },
          "defaultProperties": [
          ],
          "type": "object"
        },
        "outputValuesByStatus": {
          "additionalProperties": {
            "additionalProperties": {
              "type": "number"
            },
            "defaultProperties": [
            ],
            "type": "object"
          },
          "defaultProperties": [
          ],
          "type": "object"
        },
        "outputsByName": {
          "additionalProperties": {
            "anyOf": [
              {
                "defaultProperties": [
                ],
                "properties": {
                  "inverted": {
                    "type": "boolean"
                  },
                  "mode": {
                    "enum": [
                      "ON_OFF",
                      "PWM"
                    ],
                    "type": "string"
                  },
                  "pin": {
                    "type": "number"
                  },
                  "range": {
                    "type": "number"
                  }
                },
                "required": [
                  "pin"
                ],
                "type": "object"
              },
              {
                "type": "number"
              }
            ]
          },
          "defaultProperties": [
          ],
          "type": "object"
        }
      },
      "type": "object"
    },
    "defaultStatus": {
      "type": "string"
    },
    "service": {
      "defaultProperties": [
      ],
      "properties": {
        "name": {
          "type": "string"
        },
        "port": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "statuses": {
      "items": {
        "type": "string"
      },
      "type": "array"
    }
  },
  "required": [
    "box",
    "defaultStatus",
    "statuses"
  ],
  "type": "object"
};
export type ValidateFunction<T> = ((data: unknown) => data is T) & Pick<Ajv.ValidateFunction, 'errors'>
export const isRawConfig = ajv.compile(RawConfigSchema) as ValidateFunction<RawConfig>;
export default function validate(value: unknown): RawConfig {
  if (isRawConfig(value)) {
    return value;
  } else {
    throw new Error(
      ajv.errorsText(isRawConfig.errors!.filter((e: any) => e.keyword !== 'if'), {dataVar: 'RawConfig'}) +
      '\n\n' +
      inspect(value),
    );
  }
}
