# I chose these pins to be next to each other from pins that are not reserved for alternate
# functions this is where they are on the board:
#
# <---top-side--+
#       -----   |
#     3v3 | 5v  |
#       2 | 5v  | r
#       3 | G   | i
#       4 | 14  | g
#       G | 15  | h
#    * 17 | 18  | t
#    * 27 | G   |
#    * 22 | 23 *| s
#     3v3 | 24 *| i
#      10 | G   | d
#       9 | 25  | e
#      11 | 8   |
#       G | 7   |
#       --+--   |  -- RPi 2+ only --
#       0 | 1   | |
#       5 | G   | v
#       6 | 12  |
#      13 | G   |
#      19 | 16  |
#      26 | 20  |
#       G | 21  |
#       -----   |
#               v
---
inputsByName:
  low: 23
  high: 24
outputsByName:
  red:
    mode: PWM
    pin: 17
  green:
    mode: PWM
    pin: 27
  blue:
    mode: PWM
    pin: 22
inputStatusRules:
  - status: Off
    inputConditions:
      low: 0
      high: 0
  - status: Low
    inputConditions:
      low: 1
      high: 0
  - status: High
    inputConditions:
      low: 0
      high: 1
outputValuesByStatus:
  Off:
    red: 0
    green: 255
  Low:
    red: 127
    green: 127
  High:
    red: 255
    green: 0
