## Properties with default values are commented out with single #
---
statuses:
    - off
    - party
    - yellow
    - red

defaultStatus: off

#service:
#    port: 8991
#    name: unique_bonjour_name (default is calculated based on os.hostname)

box:
    #  inputDebounceDelay: 50 # (int microseconds)
    defaultBrightness: 0.5 # (0 - 1)

    lightSensor:
        model: 'ADAFRUIT_BH1750'
    #        transform:
    #            function: 'LOG',
    #            coefficient: 0.1,
    #            xOffset: -20,
    #            yOffset: -0.25,
    #            min: 0.05,
    #            max: {defaultBrightness},

    ## I chose these pins from pins that are not reserved for alternate
    ## functions. This is where they are on the board:
    ##       top side
    ## <------------------+
    ##            -----   |
    ##          3v3 | 5v  |
    ##     SDA *  2 | 5v  | r
    ##     SCL *  3 | G   | i
    ##            4 | 14  | g
    ##            G | 15  | h
    ##      .- * 17 | 18 *| t  -.
    ## out -|  * 27 | G   |     |
    ##      `- * 22 | 23 *| s   |
    ##          3v3 | 24 *| i   |- in
    ##           10 | G   | d   |
    ##            9 | 25 *| e  -`
    ##           11 | 8   |
    ##            G | 7   |
    ##            --+--   |  -- RPi 2+ only
    ##            0 | 1   | |
    ##            5 | G   | v
    ##            6 | 12  |
    ##           13 | G   |
    ##           19 | 16  |
    ##           26 | 20  |
    ##            G | 21  |
    ##            -----   |
    ##                    v

    inputsByName:
        ## for on/off switch (toggle, rotary, etc.), use ON_OFF input type:
        #yellow:
        #    pin: 23
        #    mode: ON_OFF
        #    action: STATUS
        #    onValue: yellow
        #red:
        #    pin: 24
        #    mode: ON_OFF
        #    action: STATUS
        #    onValue: red

        ## for momentary buttons, use TRIGGER input type:
        black:
            pin: 18
            mode: TRIGGER
            action: STATUS
            onValue: off
        yellow:
            pin: 23
            mode: TRIGGER
            action: STATUS
            onValue: yellow
        red:
            pin: 24
            mode: TRIGGER
            action: STATUS
            onValue: red
        party:
            pin: 25
            mode: TRIGGER
            action: STATUS
            onValue: party

    outputsByName:
        red:
            mode: PWM
            pin: 17
        green:
            mode: PWM
            pin: 27

    outputsByStatus:
        off:
            red: 0
            green: 0
        yellow:
            red: 255
            green: 255
        red:
            red: 255
            green: 0
        party:
            red:
                function: SIN
                period: 4000
                min: 50
                max: 255
            green:
                function: SIN
                period: 3700
                min: 50
                max: 255
