## Properties with default values are commented out with single #
---
statuses:
  - standby
  - yellow
  - red
  - green

defaultStatus: standby

# service:
#   port: 8991
#   name: unique_bonjour_name (default is calculated based on os.hostname)

box:
#  inputDebounceDelay: 50000
#  defaultBrightness: 1

  ## I chose these pins to be next to each other from pins that are not reserved for alternate
  ## functions this is where they are on the board:
  ##       top side
  ## <------------------+
  ##            -----   |
  ##          3v3 | 5v  |
  ##            2 | 5v  | r
  ##            3 | G   | i
  ##            4 | 14  | g
  ##            G | 15  | h
  ##      .- * 17 | 18  | t
  ## out -|  * 27 | G   |
  ##      `- * 22 | 23 *| s  -.
  ##          3v3 | 24 *| i   |
  ##           10 | G   | d   |- in
  ##            9 | 25 *| e   |
  ##           11 | 8  *|    -`
  ##            G | 7   |
  ##            --+--   |  -- RPi 2+ only
  ##            0 | 1   | |
  ##            5 | G   | v
  ##            6 | 12  |
  ##           13 | G   |
  ##           19 | 16  |
  ##           26 | 20  |
  ##            G | 21  |
  ##            -----   |
  ##                    v

  inputsByName:
    yellow:
      pin: 23
      mode: ON_OFF
      onStatus: yellow
    red:
      pin: 24
      mode: ON_OFF
      onStatus: red

  outputsByName:
    red:
      mode: PWM
      pin: 17
    green:
      mode: PWM
      pin: 27

  outputValuesByStatus:
    standby:
      red: 0
      green: 0
    yellow:
      red: 255
      green: 225
    red:
      red: 255
      green: 0
    green:
      red: 0
      green: 255
